### ISSUE TITLE
Request to add support for Zybo Z7 in zynq.cc

### ISSUE THREAD

**Issue by ijyothi** [kernkonzept/bootstrap#3]
Hello I am trying to run the L4Re on Zybo Z7. 

Since it is a new bsp I tried to generate the defconfig file by following the guide of configuring your own bsp in L4Re documentation. 

But, even the example Hello World doesnt work on Zybo Z7 which I think is happening probably in bootstrap as the bootstraper doesnt start. 

I attach my U Boot log below

```
`U-Boot 2018.09-00427-g4024652143-dirty (Sep 01 2023 - 17:07:44 +0200)
CPU:   Zynq 7z020
Silicon: v3.1
Model: Digilent Zybo Z7 board
I2C:   ready
DRAM:  ECC disabled 1 GiB
MMC:   sdhci@e0100000: 0
Loading Environment from SPI Flash... SF: Detected s25fl128s_64k with page size 256 Bytes, erase size 64 KiB, total 16 MiB
OK
In:    serial@e0001000
Out:   serial@e0001000
Err:   serial@e0001000
Net:   ZYNQ GEM: e000b000, phyaddr 0, interface rgmii-id

Warning: ethernet@e000b000 (eth0) using random MAC address - 36:c7:49:3e:11:ce
eth0: ethernet@e000b000
Checking if uenvcmd is set ...
Hit any key to stop autoboot:  0
15130688 bytes read in 967 ms (14.9 MiB/s)
11258 bytes read in 14 ms (785.2 KiB/s)
## Booting kernel from Legacy Image at 03000000 ...
   Image Name:   L4 Image #30
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    15130624 Bytes = 14.4 MiB
   Load Address: 01000000
   Entry Point:  01000000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 02a00000
   Booting using the fdt blob at 0x2a00000
   Loading Kernel Image ... OK
   Loading Device Tree to 3eb2a000, end 3eb2fbf9 ... OK

Starting kernel ...`
```

Any advice on how to adapt the zynq.cc Uart etc for this to work?

**Comment by admlck** [comment]
Hi,
looks like this is using the second UART. Could you try generating the uimage with PLATFORM_UART_NR=1 ?

**Comment by ijyothi** [comment]
Hi, thank you very much for the reply. 

So the defconfig has the PLATFORM_UART_NR=1 which is same as that of Zedboard. Only the RAM size of Zybo becomes 1024 MB , as I understand the documentation. Hence I think it comes from the UART definition in the zynq.cc file. How are the values for Zedboard calculated? I didn’t quite understand that. 

Thanks for the help!

**Comment by ijyothi** [comment]
Hello,
To reproduce this, I am using the PT= Zedboard and its CPU type etc  for this build. I also am using a very simple dts. 
I cannot seem to grep to the error `Warning: Sigma0 raised an exception --> HALT
Panic: ...`
I am attaching the files you requested to this issue. 

Hope to fix this soon, thanks

**Comment by admlck** [comment]
Hi,
to cross check, does it work in QEMU?
With: qemu-system-arm -kernel images/bootstrap.elf -serial null -serial stdio -m 512 -M xilinx-zynq-a9
For debugging your fiasco and sigma0 binaries are also useful.
Thanks.

**Comment by ijyothi** [comment]
Hello

Thanks for the update. No, I have not worked on qemu as my main goal was to do sd boot on the hardware. But if you insist, I can try. 

I am also attaching the binaries you requested. 
[bin.zip](https://github.com/kernkonzept/bootstrap/files/14647214/bin.zip)

Thanks

**Comment by admlck** [comment]
Can you please also attach the generated bootstrap.elf? Note that I do not have your board, I'm merely trying to reproduce your issue with the means I have (QEMU).

**Comment by ijyothi** [comment]
Hello, yes thanks for the help. 

I am attaching the([bootstrap.zip](https://github.com/kernkonzept/bootstrap/files/14694911/bootstrap.zip)) I am using. Upon further searching I found that the page fault happens in this file [ here in fiasco](https://github.com/kernkonzept/fiasco/blob/f5dc138f27303e951368d9d2b99a2ef8f93c848f/src/kern/thread-pagefault.cpp#L91), can you direct me as to why this happens and if i can override this? Also FYI, I am using RAM_SIZE=1024MB, does this have anything to do with [these](https://github.com/kernkonzept/fiasco/blob/master/src/kern/arm/bsp/zynq/mem_layout-arm-zynq.cpp) ?

**Comment by ijyothi** [comment]
I tried running on Qemu and end up getting stuck here now..
![image](https://github.com/kernkonzept/bootstrap/assets/43724339/a4867fa4-3768-410b-af31-3f601bc6ebb5)

**Comment by admlck** [comment]
Could you please update your fiasco repository (from github) and rebuild? I have fixed this particular issue I believe.

**Comment by ijyothi** [comment]
Hello , I tried with the latest Fiasco, but it still fails at sigma 0 exception. 
[bootstrap (2).zip](https://github.com/kernkonzept/bootstrap/files/14731988/bootstrap.2.zip)

![image](https://github.com/kernkonzept/bootstrap/assets/43724339/a61cd309-b538-4998-a975-6bdf91276c6d)

**Comment by admlck** [comment]
Could you also please update all of the other repos as well? We recently changed the kernel invocation mechanism and I see sigma0 using the previous (old) method.

**Comment by ijyothi** [comment]
Hello, thanks for the information and your constant advice. I happened to rebuild from the github, previously I was using the 2023 Snapshot, and now it boots on qemu machine for me. Although the same elf file still doesnt boot on the board from sd card. Do you happen to have an idea why this inconsistency?
Qemu>
![image](https://github.com/kernkonzept/bootstrap/assets/43724339/c9cdcf3d-df2c-4493-baed-41bc48c66a3b)

Uboot of sd boot>
![image](https://github.com/kernkonzept/bootstrap/assets/43724339/569b480b-1e08-4337-baed-f05fbc0ca817)

**Comment by admlck** [comment]
Hi, we can try to figure it out what the difference might be. First thing would be to see what's on f003c96c. Could you share the fiasco / bootstrap.elf file that you use on the target?

**Comment by ijyothi** [comment]
Hello, here are the files I am working with. I m thinking perhaps it could be the address mismatch from zedboard to zybo, although I am not sure. Thanks for the support.
[files.zip](https://github.com/kernkonzept/bootstrap/files/14742380/files.zip)

**Comment by admlck** [comment]
Ok, one more, also please the fiasco.debug file :)

**Comment by ijyothi** [comment]
Attaching with the debug file. 
[Uploading files.zip…]()

**Comment by admlck** [comment]
Is the link ok? It just points to this issue's URL...

**Comment by admlck** [comment]
The fault happens in the CPU boot-up of the second core. Does it work if you disable multi-processing in the fiasco config?
Does the Zybo have one or two cores?

**Comment by admlck** [comment]
Yes, it's in the menuconfig.

**Comment by ijyothi** [comment]
Yes! that solved it!
Thank you so much for this support! 

![image](https://github.com/kernkonzept/bootstrap/assets/43724339/d3113e1d-74ae-457f-8e58-82cbd0be6ce1)
